name: Build FAP

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Checkout Flipper firmware
        uses: actions/checkout@v4
        with:
          repository: flipperdevices/flipperzero-firmware
          path: firmware
          submodules: recursive

      - name: Place app into applications_user
        run: |
          mkdir -p firmware/applications_user/nfc_compare
          cp application.fam nfc_compare.c nfc_compare_io.c nfc_compare_io.h firmware/applications_user/nfc_compare/

            - name: Build (Docker)
        uses: addnab/docker-run-action@v3
        with:
          image: ghcr.io/flipperdevices/flipperzero-toolchain:nightly
          options: -v ${{ github.workspace }}/firmware:/work -w /work
          run: |
            ./fbt fap_nfc_compare

      - name: Find artifact
        id: find
        run: |
          path=$(find firmware/build -iname "*NFC*Compare*.fap" | head -n1)
          echo "artifact=$path" >> $GITHUB_OUTPUT

      - name: Upload artifact to Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.run_number }}
          files: ${{ steps.find.outputs.artifact }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
